### ISSUE TITLE
Install cursor theme

### ISSUE THREAD

**Issue by MichaelTiebesl** [numixproject/numix-cursor-theme#2]
How do i install the cursor theme on Ubuntu 16.10? I have the icons installed by PPA. Just the default icons Numix and Numix Circle. I already downloaded the numix-cursor-theme and put the folder Numix from the downloaded file into the default Numix icons folder but no success with that. Thanks.

**Comment by Foggalong** [comment]
I've updated the installation instructions in the README to be more thorough :+1:
